# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: parameters.yaml }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Parsers,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    registry.parser.site:
        class: App\Parsers\Sites\SiteParserRegistry
        tags: ['system.registry']

    registry.parser.videoResource:
        class: App\Parsers\VideoResources\VideoResourceParserRegistry
        tags: ['system.registry']

    registry.formatter:
        class: App\Formatter\FormatterRegistry
        tags: ['system.registry']

    App\Parsers\Sites\SiteParserRegistry:
        alias: registry.parser.site

    App\Parsers\VideoResources\VideoResourceParserRegistry:
        alias: registry.parser.videoResource

    App\Formatter\FormatterRegistry:
        alias: registry.formatter

    App\Parsers\Sites\ColdfilmParser:
        tags: ['registry.parser.site']

    App\Parsers\VideoResources\VioToParser:
        tags: ['registry.parser.videoResource']

    App\Parsers\VideoResources\ColdfilmOnlineParser:
        tags: ['registry.parser.videoResource']

    App\Parsers\PlaylistParser:

    App\Formatter\SerialListFormatter:
        tags: ['registry.formatter']

    App\Repository\RatingRepository:
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - App\Entity\Rating

    App\Repository\SerialRepository:
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - App\Entity\Serial